language: python
sudo: false

python:
  - "3.7"


install:
  - pip install coverage
  - pip install -e . 

script:
  - coverage run amplicov --help
  - coverage run amplicov --version
  - coverage run amplicov --bed tests/input.bed --cov tests/coverage.txt --prefix output --outdir tests/output 

after_success:
bash <(curl -s https://codecov.io/bash)

